### ISSUE TITLE
no registries found

### ISSUE THREAD

**Issue by 2-www** [marhkb/pods#790]
i have the flatpak on debian

the gui says "no registries found" when i try to download an image, but the cli works (`podman pull ubuntu`, for example)

**Comment by wvovaw** [comment]
@2-www I just faced the same issue and luckily got it solved. Here's what I did

1. created `~/.config/containers/registries.conf` with the following content

 ```toml
unqualified-search-registries = ["docker.io", "quay.io"]

[[registry]]
location = "docker.io"
prefix = "*.docker.io"
insecure = false
blocked = false
```

This didn't work until I

2. downloaded an image via cli

```sh
podman pull redis
```

After this I'm able to search and install images right in the app
